(()=>{'use strict';
  const $=s=>document.querySelector(s),portal=()=>window.SummitPortal;
  const words={en:{kicker:'Student enrollment',intro:"Enter the student's legal information and record the signed enrollment consent.",legalName:'Student legal name',studentEmail:'Student email',studentPhone:'Student phone',language:'Preferred language',birthDate:'Date of birth',gender:'Gender',address:'Home address',licence:"Driver's licence number",courseStart:'Course start date',emergencyName:'Emergency contact name',relationship:'Relationship',emergencyPhone:'Emergency contact phone',signerName:'Consent signer name',signerRelationship:'Signer relationship',enrollmentConsent:'The signer consents to enrollment in the Summit program and confirms the information is accurate.',privacyConsent:"The signer acknowledges Summit's privacy and student-record practices.",electronicConsent:'The signer consents to electronic training records, signatures, and communications.',attestation:'The signer entered their name and confirmed these consents in the presence of Summit staff.',inviteParent:'Send a secure family-portal invitation after enrollment',parentName:'Parent or guardian name',parentEmail:'Parent or guardian email',save:'Complete student enrollment'},fr:{kicker:'Inscription de l’élève',intro:'Saisissez les renseignements légaux de l’élève et consignez le consentement signé.',legalName:'Nom légal de l’élève',studentEmail:'Courriel de l’élève',studentPhone:'Téléphone de l’élève',language:'Langue préférée',birthDate:'Date de naissance',gender:'Genre',address:'Adresse du domicile',licence:'Numéro de permis de conduire',courseStart:'Date de début du cours',emergencyName:'Nom du contact d’urgence',relationship:'Lien',emergencyPhone:'Téléphone du contact d’urgence',signerName:'Nom du signataire',signerRelationship:'Lien du signataire',enrollmentConsent:'Le signataire consent à l’inscription au programme Summit et confirme l’exactitude des renseignements.',privacyConsent:'Le signataire reconnaît les pratiques de Summit en matière de confidentialité et de dossiers.',electronicConsent:'Le signataire consent aux dossiers, signatures et communications électroniques.',attestation:'Le signataire a saisi son nom et confirmé ces consentements en présence du personnel Summit.',inviteParent:'Envoyer une invitation sécurisée au portail familial après l’inscription',parentName:'Nom du parent ou tuteur',parentEmail:'Courriel du parent ou tuteur',save:'Terminer l’inscription de l’élève'}};
  const language=()=>document.documentElement.lang==='fr'?'fr':'en';
  function translate(){document.querySelectorAll('[data-onboard]').forEach(el=>el.textContent=words[language()][el.dataset.onboard]||el.textContent)}
  function close(){form.classList.add('hidden');$('#modalBackdrop').classList.add('hidden')}
  const form=$('#onboardingForm');
  window.addEventListener('summit:onboard-registration',e=>{const r=e.detail.registration;form.reset();form.elements.registration_id.value=r.id;form.elements.legal_name.value=r.name||'';form.elements.student_email.value=r.email||'';form.elements.student_phone.value=r.phone||'';form.elements.preferred_language.value=String(r.language||'en').toLowerCase().startsWith('fr')?'fr':'en';form.elements.parent_name.value=r.name||'';form.elements.parent_email.value=r.email||'';$('#onboardingTitle').textContent=`${language()==='fr'?'Compléter l’inscription':'Complete enrollment'} — ${r.name}`;form.querySelector('.message').textContent='';translate();form.classList.remove('hidden');$('#modalBackdrop').classList.remove('hidden')});
  form.addEventListener('submit',async e=>{e.preventDefault();const button=e.submitter,data=new FormData(form),registrationId=data.get('registration_id'),payload=Object.fromEntries(data.entries());delete payload.registration_id;['enrollment_consent','privacy_consent','electronic_records_consent','signer_attested','invite_parent'].forEach(k=>payload[k]=data.get(k)==='on');if(payload.invite_parent&&(!payload.parent_name||!payload.parent_email)){form.querySelector('.message').textContent=language()==='fr'?'Le nom et le courriel du parent sont requis pour envoyer l’invitation.':'Parent name and email are required to send the invitation.';return}button.disabled=true;const {data:result,error}=await portal().client.rpc('complete_registration_onboarding',{p_registration_id:registrationId,p_payload:payload});if(error){button.disabled=false;form.querySelector('.message').textContent=error.message;return}let invitationSent=false;if(result.parent_invitation_requested){const invited=await portal().client.functions.invoke('invite-parent',{body:{student_id:result.student_id,full_name:result.parent_name,email:result.parent_email,preferred_language:result.preferred_language}});if(invited.error){button.disabled=false;form.querySelector('.message').textContent=`Enrollment completed, but the family invitation failed: ${invited.error.message}`;return}invitationSent=Boolean(invited.data?.invitation_sent)}button.disabled=false;close();$('#portalMessage').textContent=language()==='fr'?(invitationSent?'Inscription terminée et invitation familiale envoyée.':'Inscription de l’élève terminée.'):(invitationSent?'Student enrollment completed and family invitation sent.':'Student enrollment completed.');location.reload()});
  new MutationObserver(translate).observe(document.documentElement,{attributes:true,attributeFilter:['lang']});translate();
})();
