(() => {
  'use strict';
  const t = {
    en:{portalName:'Instructor Portal',signOut:'Sign out',privateAccess:'Private staff access',welcome:'Welcome to the Summit instructor portal.',loginIntro:'Sign in to view assigned students, record lessons, and update progress.',email:'Email',password:'Password',signIn:'Sign in securely',dashboard:'Dashboard',assignedStudents:'Assigned students',upcomingLessons:'Upcoming lessons',activeStudents:'Active students',studentRoster:'Student roster',yourStudents:'Your students',addStudent:'Add student',noStudents:'No students are assigned yet.',selectStudent:'Select a student to review progress and record a lesson.',studentProgress:'Student progress',onlineTraining:'Online training',inCarTraining:'In-car training',summitScore:'Summit score',currentFocus:'Current focus',nextLesson:'Next lesson',recordLesson:'Record a lesson',fullName:'Full name',phone:'Phone',language:'Language',assignInstructor:'Assign instructor',saveStudent:'Save student',lessonReport:'Lesson report',lessonDate:'Lesson date',duration:'Duration (minutes)',overallScore:'Overall score',observation:'Observation',intersections:'Intersections',laneControl:'Lane control',parking:'Parking',defensiveDriving:'Defensive driving',lessonNotes:'Instructor notes (shared with parent)',nextFocus:'Next focus',saveReport:'Save lesson report',owner:'Owner',manager:'Manager',instructor:'Instructor',active:'Active',completed:'Completed',pre_registered:'Pre-registered',inactive:'Inactive',hours:'hours',saved:'Saved successfully.',authFailed:'The email or password is incorrect.',notAuthorized:'This account does not have active Summit staff access.',loadFailed:'The portal could not load. Please try again.'},
    fr:{portalName:'Portail des moniteurs',signOut:'Déconnexion',privateAccess:'Accès privé du personnel',welcome:'Bienvenue au portail des moniteurs Summit.',loginIntro:'Connectez-vous pour voir les élèves assignés, consigner les leçons et mettre à jour leur progrès.',email:'Courriel',password:'Mot de passe',signIn:'Connexion sécurisée',dashboard:'Tableau de bord',assignedStudents:'Élèves assignés',upcomingLessons:'Leçons à venir',activeStudents:'Élèves actifs',studentRoster:'Liste des élèves',yourStudents:'Vos élèves',addStudent:'Ajouter un élève',noStudents:'Aucun élève ne vous est assigné.',selectStudent:'Sélectionnez un élève pour consulter son progrès et consigner une leçon.',studentProgress:'Progrès de l’élève',onlineTraining:'Formation en ligne',inCarTraining:'Formation en voiture',summitScore:'Résultat Summit',currentFocus:'Objectif actuel',nextLesson:'Prochaine leçon',recordLesson:'Consigner une leçon',fullName:'Nom complet',phone:'Téléphone',language:'Langue',assignInstructor:'Assigner un moniteur',saveStudent:'Enregistrer l’élève',lessonReport:'Rapport de leçon',lessonDate:'Date de la leçon',duration:'Durée (minutes)',overallScore:'Note globale',observation:'Observation',intersections:'Intersections',laneControl:'Maîtrise de la voie',parking:'Stationnement',defensiveDriving:'Conduite préventive',lessonNotes:'Notes du moniteur (partagées avec le parent)',nextFocus:'Prochain objectif',saveReport:'Enregistrer le rapport',owner:'Propriétaire',manager:'Gestionnaire',instructor:'Moniteur',active:'Actif',completed:'Terminé',pre_registered:'Préinscrit',inactive:'Inactif',hours:'heures',saved:'Enregistré avec succès.',authFailed:'Le courriel ou le mot de passe est incorrect.',notAuthorized:'Ce compte ne dispose pas d’un accès actif au personnel Summit.',loadFailed:'Le portail n’a pas pu être chargé. Veuillez réessayer.'}
  };
  Object.assign(t.en,{secureSetup:'Secure account setup',createPassword:'Create your secure password.',setupIntro:'Choose a unique password for the Summit portal. Do not reuse your Gmail password.',newPassword:'New password',confirmPassword:'Confirm new password',savePassword:'Save password and enter portal',passwordGuidance:'Use at least 12 characters, including a mix of words, numbers, or symbols.',passwordMismatch:'The passwords do not match.',passwordTooShort:'Your password must contain at least 12 characters.',passwordSaved:'Your password has been saved securely.',setupFailed:'Your password could not be saved. Please request a new invitation.'});
  Object.assign(t.fr,{secureSetup:'Configuration sécurisée du compte',createPassword:'Créez votre mot de passe sécurisé.',setupIntro:'Choisissez un mot de passe unique pour le portail Summit. Ne réutilisez pas votre mot de passe Gmail.',newPassword:'Nouveau mot de passe',confirmPassword:'Confirmer le nouveau mot de passe',savePassword:'Enregistrer le mot de passe et accéder au portail',passwordGuidance:'Utilisez au moins 12 caractères, avec un mélange de mots, de chiffres ou de symboles.',passwordMismatch:'Les mots de passe ne correspondent pas.',passwordTooShort:'Votre mot de passe doit contenir au moins 12 caractères.',passwordSaved:'Votre mot de passe a été enregistré de façon sécurisée.',setupFailed:'Votre mot de passe n’a pas pu être enregistré. Veuillez demander une nouvelle invitation.'});
  Object.assign(t.en,{changePassword:'Password',accountSecurity:'Account security',changePasswordIntro:'Choose a unique password for the Summit portal. Do not reuse your email password.',saveNewPassword:'Save new password'});
  Object.assign(t.fr,{changePassword:'Mot de passe',accountSecurity:'Sécurité du compte',changePasswordIntro:'Choisissez un mot de passe unique pour le portail Summit. Ne réutilisez pas votre mot de passe de courriel.',saveNewPassword:'Enregistrer le nouveau mot de passe'});
  Object.assign(t.en,{weekRequests:'Week requests',preferredTrainingWeeks:'Preferred training weeks',noWeekRequests:'No preferred weeks have been requested yet.',requestedWeek:'Requested week',founding:'Founding 30',regular:'Regular'});
  Object.assign(t.fr,{weekRequests:'Demandes de semaines',preferredTrainingWeeks:'Semaines de formation préférées',noWeekRequests:'Aucune semaine préférée n’a encore été demandée.',requestedWeek:'Semaine demandée',founding:'30 fondateurs',regular:'Régulier'});
  Object.assign(t.en,{preferredInstructor:'Preferred instructor',confirmSchedule:'Confirm week',confirmed:'Confirmed',requested:'Requested',confirmedInstructor:'Confirmed instructor',confirmedWeek:'Confirmed training week',noPreference:'No preference',jason:'Jason St. Louis',karen:'Karen St. Pierre',scheduleConflict:'That instructor already has three students confirmed for this week.',scheduleSaved:'The instructor and training week are confirmed.'});
  Object.assign(t.fr,{preferredInstructor:'Moniteur préféré',confirmSchedule:'Confirmer la semaine',confirmed:'Confirmé',requested:'Demandé',confirmedInstructor:'Moniteur confirmé',confirmedWeek:'Semaine de formation confirmée',noPreference:'Aucune préférence',jason:'Jason St. Louis',karen:'Karen St. Pierre',scheduleConflict:'Ce moniteur a déjà trois élèves confirmés pour cette semaine.',scheduleSaved:'Le moniteur et la semaine de formation sont confirmés.'});
  Object.assign(t.en,{roadTestReadiness:'Road-test readiness'});
  Object.assign(t.fr,{roadTestReadiness:'Préparation à l’examen routier'});
  Object.assign(t.en,{lessonNotes:'Private instructor notes (staff only)',parentSummary:'Parent progress summary',shareWithParent:'Share this lesson summary and scores with the parent dashboard'});
  Object.assign(t.fr,{lessonNotes:'Notes privées du moniteur (personnel seulement)',parentSummary:'Résumé des progrès pour les parents',shareWithParent:'Partager ce résumé de leçon et les notes avec le tableau de bord des parents'});
  Object.assign(t.en,{studentSignature:'Student signature (student types full name)',instructorSignature:'Instructor signature',studentSignatureAttestation:'The student entered their name after completing this lesson and confirmed this record.',instructorSignatureAttestation:'I confirm that I provided this lesson and that this record is accurate.'});
  Object.assign(t.fr,{studentSignature:'Signature de l’élève (l’élève saisit son nom complet)',instructorSignature:'Signature du moniteur',studentSignatureAttestation:'L’élève a saisi son nom après avoir terminé cette leçon et a confirmé ce dossier.',instructorSignatureAttestation:'Je confirme avoir donné cette leçon et que ce dossier est exact.'});
  Object.assign(t.en,{connectParent:'Connect parent',familyAccess:'Family access',parentInviteIntro:'Connect this student to a protected family account. A secure invitation will be emailed to the parent.',parentName:'Parent or guardian name',parentEmail:'Parent or guardian email',sendParentInvite:'Send secure invitation',parentInviteSent:'The family account is connected and the secure invitation was sent.',parentConnected:'The existing family account is now connected to this student.'});
  Object.assign(t.fr,{connectParent:'Lier un parent',familyAccess:'Accès familial',parentInviteIntro:'Liez cet élève à un compte familial protégé. Une invitation sécurisée sera envoyée au parent par courriel.',parentName:'Nom du parent ou tuteur',parentEmail:'Courriel du parent ou tuteur',sendParentInvite:'Envoyer l’invitation sécurisée',parentInviteSent:'Le compte familial est lié et l’invitation sécurisée a été envoyée.',parentConnected:'Le compte familial existant est maintenant lié à cet élève.'});
  Object.assign(t.en,{scheduleLesson:'Schedule lesson',lessonSchedule:'Lesson schedule',scheduleIntro:"Choose the student's next lesson date, time, and duration.",lessonDateTime:'Lesson date and time',scheduledDuration:'Lesson duration (minutes)',saveSchedule:'Save schedule',scheduleSaved:'The lesson schedule has been saved.',lessonConflict:'That instructor already has an overlapping lesson. Choose another time.',dailyLimitReached:'That instructor already has three students scheduled for this day. Choose another day.'});
  Object.assign(t.fr,{scheduleLesson:'Planifier une leçon',lessonSchedule:'Horaire de la leçon',scheduleIntro:'Choisissez la date, l’heure et la durée de la prochaine leçon de l’élève.',lessonDateTime:'Date et heure de la leçon',scheduledDuration:'Durée de la leçon (minutes)',saveSchedule:'Enregistrer l’horaire',scheduleSaved:'L’horaire de la leçon a été enregistré.',lessonConflict:'Ce moniteur a déjà une leçon qui se chevauche. Choisissez une autre heure.',dailyLimitReached:'Ce moniteur a déjà trois élèves prévus cette journée. Choisissez une autre journée.'});
  Object.assign(t.en,{lessonCalendar:'Lesson calendar',upcomingSchedule:'Upcoming schedule',noUpcomingLessons:'No upcoming lessons are scheduled.'});
  Object.assign(t.fr,{lessonCalendar:'Calendrier des leçons',upcomingSchedule:'Horaire à venir',noUpcomingLessons:'Aucune leçon à venir n’est planifiée.'});
  Object.assign(t.en,{rescheduleLesson:'Reschedule lesson',cancelLesson:'Cancel lesson',cancelLessonConfirm:'Cancel this scheduled lesson?',lessonCancelled:'The lesson has been cancelled.'});
  Object.assign(t.fr,{rescheduleLesson:'Replanifier la leçon',cancelLesson:'Annuler la leçon',cancelLessonConfirm:'Annuler cette leçon planifiée?',lessonCancelled:'La leçon a été annulée.'});
  Object.assign(t.en,{scheduleSavedAndNotified:'The schedule was saved and email notifications were sent.',scheduleSavedEmailFailed:'The schedule was saved, but email notifications could not be sent.',lessonCancelledAndNotified:'The lesson was cancelled and email notifications were sent.',lessonCancelledEmailFailed:'The lesson was cancelled, but email notifications could not be sent.'});
  Object.assign(t.fr,{scheduleSavedAndNotified:'L’horaire a été enregistré et les avis par courriel ont été envoyés.',scheduleSavedEmailFailed:'L’horaire a été enregistré, mais les avis par courriel n’ont pas pu être envoyés.',lessonCancelledAndNotified:'La leçon a été annulée et les avis par courriel ont été envoyés.',lessonCancelledEmailFailed:'La leçon a été annulée, mais les avis par courriel n’ont pas pu être envoyés.'});
  const $ = s => document.querySelector(s);
  const config = window.SUMMIT_PORTAL_CONFIG;
  const client = window.supabase.createClient(config.supabaseUrl, config.supabasePublishableKey);
  const studentFields='id,instructor_id,full_name,email,phone,preferred_language,status,online_hours,classroom_hours,flexible_hours,in_car_hours,summit_score,road_test_readiness,current_focus,next_lesson_at,created_by,created_at,updated_at,registration_id,assigned_instructor_code,training_week_start,scheduled_duration_minutes';
  let lang = localStorage.getItem('summitPortalLanguage') || (location.pathname.includes('/fr/') ? 'fr' : 'en');
  let profile = null, students = [], registrations = [], instructors = [], selected = null;

  window.SummitPortal = {
    get client(){return client},
    get profile(){return profile},
    get students(){return students},
    get instructors(){return instructors},
    get selected(){return selected},
    get studentFields(){return studentFields},
    setStudents(next){students=next;updateStats();renderStudents();if(selected)selected=students.find(s=>s.id===selected.id)||null;if(selected)renderDetail(selected)}
  };

  function translate(){document.documentElement.lang=lang;document.querySelectorAll('[data-i18n]').forEach(el=>{el.textContent=t[lang][el.dataset.i18n]});$('#languageToggle').textContent=lang==='en'?'FR':'EN';localStorage.setItem('summitPortalLanguage',lang);renderStudents();renderCalendar();renderRegistrations();if(selected)renderDetail(selected)}
  function message(el,text,error=false){el.textContent=text;el.classList.toggle('error',error)}
  function openModal(id){$('#'+id).classList.remove('hidden');$('#modalBackdrop').classList.remove('hidden')}
  function closeModals(){document.querySelectorAll('.modal-card').forEach(x=>x.classList.add('hidden'));$('#modalBackdrop').classList.add('hidden')}
  function dateText(value){if(!value)return '—';return new Intl.DateTimeFormat(lang==='fr'?'fr-CA':'en-CA',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value))}
  function weekText(value){if(!value)return '—';const start=new Date(`${value}T12:00:00`),end=new Date(start);end.setDate(end.getDate()+4);const format=new Intl.DateTimeFormat(lang==='fr'?'fr-CA':'en-CA',{month:'short',day:'numeric',year:'numeric'});return `${format.format(start)} – ${format.format(end)}`}
  function instructorText(value,userId){return ({no_preference:t[lang].noPreference,jason_st_louis:t[lang].jason,karen_st_pierre:t[lang].karen})[value]||instructors.find(x=>x.user_id===userId)?.full_name||(profile&&profile.user_id===userId?profile.full_name:'—')}
  function statusText(value){return t[lang][value]||value}
  function isPasswordSetupLink(){const params=`${location.search}&${location.hash.replace(/^#/,'')}`;return /(?:^|[?&#])(type=(?:invite|recovery)|access_token=|code=)/.test(params)}
  function showPasswordSetup(){
    $('#loginView').classList.add('hidden');
    $('#portalView').classList.add('hidden');
    $('#passwordSetupView').classList.remove('hidden');
    $('#signOutButton').classList.add('hidden');
  }

  async function loadPortal(user){
    const {data:p,error:pe}=await client.from('staff_profiles').select('user_id,full_name,role,preferred_language,is_active').eq('user_id',user.id).maybeSingle();
    if(pe||!p||!p.is_active){await client.auth.signOut();message($('#loginMessage'),t[lang].notAuthorized,true);return}
    profile=p;lang=p.preferred_language||lang;translate();
    const {data:s,error:se}=await client.from('students').select(studentFields).order('full_name');
    if(se){message($('#portalMessage'),t[lang].loadFailed,true);return}
    students=s||[];$('#loginView').classList.add('hidden');$('#portalView').classList.remove('hidden');$('#signOutButton').classList.remove('hidden');$('#changePasswordButton').classList.remove('hidden');
    const canManage=p.role==='owner'||p.role==='manager';
    $('#staffGreeting').textContent=p.full_name;$('#staffRole').textContent=t[lang][p.role];$('#newStudentButton').classList.toggle('hidden',!canManage);$('#scheduleLessonButton').classList.toggle('hidden',!canManage);$('#connectParentButton').classList.toggle('hidden',!canManage);
    updateStats();renderStudents();if(students[0])selectStudent(students[0].id);
    if(canManage){await Promise.all([loadInstructors(),loadRegistrations()]);window.dispatchEvent(new CustomEvent('summit:portal-ready',{detail:{canManage:true}}));}
  }
  async function loadRegistrations(){const {data,error}=await client.from('registrations').select('id,name,email,phone,language,tuition_tier,preferred_instructor,preferred_week_start,scheduling_status,confirmed_student_id,created_at').order('created_at',{ascending:false});if(error)return message($('#portalMessage'),t[lang].loadFailed,true);registrations=data||[];$('#registrationPanel').classList.remove('hidden');renderRegistrations()}
  async function loadInstructors(){const {data}=await client.from('staff_profiles').select('user_id,full_name,role,provides_instruction,driver_licence_number,driver_licence_expiry,instructor_licence_number,instructor_licence_expiry').eq('is_active',true).order('full_name');instructors=data||[];$('#instructorSelect').innerHTML=instructors.map(x=>`<option value="${x.user_id}">${escapeHtml(x.full_name)} — ${t[lang][x.role]}</option>`).join('');renderCalendar();if(selected)renderDetail(selected)}
  function updateStats(){const now=Date.now(),upcoming=students.filter(x=>x.next_lesson_at&&new Date(x.next_lesson_at).getTime()>now);$('#studentCount').textContent=students.length;$('#activeCount').textContent=students.filter(x=>x.status==='active').length;$('#upcomingCount').textContent=upcoming.length;renderCalendar()}
  function escapeHtml(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
  function renderStudents(){if(!$('#studentList'))return;$('#studentList').innerHTML=students.map(s=>`<button class="student-button ${selected&&selected.id===s.id?'active':''}" data-student="${s.id}" type="button"><span>${escapeHtml(s.full_name)}<small>${escapeHtml(s.current_focus||statusText(s.status))}</small></span><b>${s.in_car_hours}/10</b></button>`).join('');$('#emptyStudents').classList.toggle('hidden',students.length>0)}
  function renderCalendar(){if(!$('#calendarList'))return;const upcoming=students.filter(s=>s.next_lesson_at&&new Date(s.next_lesson_at).getTime()>Date.now()).sort((a,b)=>new Date(a.next_lesson_at)-new Date(b.next_lesson_at)),dateFormat=new Intl.DateTimeFormat(lang==='fr'?'fr-CA':'en-CA',{weekday:'short',month:'short',day:'numeric'}),timeFormat=new Intl.DateTimeFormat(lang==='fr'?'fr-CA':'en-CA',{hour:'numeric',minute:'2-digit'});$('#calendarCount').textContent=upcoming.length;$('#calendarList').innerHTML=upcoming.map(s=>{const when=new Date(s.next_lesson_at),end=new Date(when.getTime()+(s.scheduled_duration_minutes||120)*60000);return `<button class="calendar-row" data-calendar-student="${s.id}" type="button"><span class="calendar-date"><strong>${escapeHtml(dateFormat.format(when))}</strong><small>${escapeHtml(timeFormat.format(when))} – ${escapeHtml(timeFormat.format(end))}</small></span><span class="calendar-student"><strong>${escapeHtml(s.full_name)}</strong><small>${escapeHtml(s.current_focus||statusText(s.status))}</small></span><span class="calendar-instructor"><small>${t[lang].confirmedInstructor}</small><strong>${escapeHtml(instructorText(s.assigned_instructor_code,s.instructor_id))}</strong></span></button>`}).join('');$('#emptyCalendar').classList.toggle('hidden',upcoming.length>0)}
  function renderRegistrations(){if(!$('#registrationList'))return;$('#registrationCount').textContent=registrations.length;$('#registrationList').innerHTML=registrations.map(r=>{const student=students.find(s=>s.registration_id===r.id);const confirmed=r.scheduling_status==='confirmed'&&student;const preferred=r.preferred_instructor==='karen_st_pierre'?'karen_st_pierre':'jason_st_louis';return `<article class="registration-row ${confirmed?'is-confirmed':''}" data-registration="${r.id}"><div class="registration-person"><strong>${escapeHtml(r.name)}</strong><small>${escapeHtml(r.email)} · ${escapeHtml(r.phone)}</small><span>${t[lang].preferredInstructor}: <b>${instructorText(r.preferred_instructor)}</b></span></div><div class="registration-request"><span>${confirmed?t[lang].confirmedWeek:t[lang].requestedWeek}</span><b>${weekText(confirmed?student.training_week_start:r.preferred_week_start)}</b></div><div class="registration-actions">${confirmed?`<em>${t[lang].confirmed}: ${instructorText(student.assigned_instructor_code)}</em>`:`<label><span>${t[lang].confirmedInstructor}</span><select class="schedule-instructor"><option value="jason_st_louis" ${preferred==='jason_st_louis'?'selected':''}>${t[lang].jason}</option><option value="karen_st_pierre" ${preferred==='karen_st_pierre'?'selected':''}>${t[lang].karen}</option></select></label><label><span>${t[lang].confirmedWeek}</span><input class="schedule-week" type="date" min="2026-10-05" step="7" value="${r.preferred_week_start||''}"></label><button class="small confirm-schedule" type="button">${t[lang].confirmSchedule}</button>`}</div><em class="tuition-tier">${t[lang][r.tuition_tier]||r.tuition_tier}</em></article>`}).join('');$('#emptyRegistrations').classList.toggle('hidden',registrations.length>0)}
  function selectStudent(id){selected=students.find(s=>s.id===id);if(!selected)return;renderStudents();renderDetail(selected);window.dispatchEvent(new CustomEvent('summit:student-selected',{detail:{student:selected}}))}
  function renderDetail(s){$('#studentEmptyState').classList.add('hidden');$('#studentDetail').classList.remove('hidden');$('#detailName').textContent=s.full_name;$('#detailStatus').textContent=statusText(s.status);$('#classroomProgress').value=Number(s.classroom_hours||0);$('#classroomValue').textContent=`${Number(s.classroom_hours||0)}/20 ${t[lang].hours}`;$('#flexibleProgress').value=Number(s.flexible_hours||0);$('#flexibleValue').textContent=`${Number(s.flexible_hours||0)}/10 ${t[lang].hours}`;$('#carProgress').value=s.in_car_hours;$('#carValue').textContent=`${s.in_car_hours}/10 ${t[lang].hours}`;$('#scoreProgress').value=s.summit_score||0;$('#scoreValue').textContent=s.summit_score==null?'—':`${s.summit_score}%`;$('#detailFocus').textContent=s.current_focus||'—';$('#detailNextLesson').textContent=dateText(s.next_lesson_at);$('#detailInstructor').textContent=instructorText(s.assigned_instructor_code,s.instructor_id);$('#detailWeek').textContent=weekText(s.training_week_start);$('#detailReadiness').textContent=s.road_test_readiness==null?'—':`${s.road_test_readiness}%`;$('#scheduleLessonButton').textContent=s.next_lesson_at?t[lang].rescheduleLesson:t[lang].scheduleLesson}

  $('#loginForm').addEventListener('submit',async e=>{e.preventDefault();message($('#loginMessage'),'');const button=e.submitter;button.disabled=true;const {data,error}=await client.auth.signInWithPassword({email:$('#email').value.trim(),password:$('#password').value});button.disabled=false;if(error)return message($('#loginMessage'),t[lang].authFailed,true);await loadPortal(data.user)});
  $('#passwordSetupForm').addEventListener('submit',async e=>{
    e.preventDefault();
    const button=e.submitter,newPassword=$('#newPassword').value,confirmation=$('#confirmPassword').value;
    message($('#passwordSetupMessage'),'');
    if(newPassword.length<12)return message($('#passwordSetupMessage'),t[lang].passwordTooShort,true);
    if(newPassword!==confirmation)return message($('#passwordSetupMessage'),t[lang].passwordMismatch,true);
    button.disabled=true;
    const {data,error}=await client.auth.updateUser({password:newPassword});
    button.disabled=false;
    if(error)return message($('#passwordSetupMessage'),t[lang].setupFailed,true);
    message($('#passwordSetupMessage'),t[lang].passwordSaved);
    history.replaceState(null,'',location.pathname);
    $('#newPassword').value='';$('#confirmPassword').value='';
    await loadPortal(data.user);
  });
  $('#signOutButton').addEventListener('click',async()=>{await client.auth.signOut();location.reload()});
  $('#changePasswordButton').addEventListener('click',()=>openModal('changePasswordForm'));
  $('#languageToggle').addEventListener('click',()=>{lang=lang==='en'?'fr':'en';translate()});
  $('#studentList').addEventListener('click',e=>{const b=e.target.closest('[data-student]');if(b)selectStudent(b.dataset.student)});
  $('#calendarList').addEventListener('click',e=>{const b=e.target.closest('[data-calendar-student]');if(!b)return;selectStudent(b.dataset.calendarStudent);$('#studentDetail').scrollIntoView({behavior:'smooth',block:'start'})});
  $('#registrationList').addEventListener('click',async e=>{const button=e.target.closest('.confirm-schedule');if(!button)return;const row=button.closest('[data-registration]'),instructor=row.querySelector('.schedule-instructor').value,week=row.querySelector('.schedule-week').value;if(!week)return message($('#portalMessage'),t[lang].loadFailed,true);button.disabled=true;message($('#portalMessage'),'');const {error}=await client.rpc('confirm_registration_schedule',{p_registration_id:row.dataset.registration,p_instructor_code:instructor,p_week_start:week});button.disabled=false;if(error)return message($('#portalMessage'),error.message.includes('three students confirmed')?t[lang].scheduleConflict:error.message,true);message($('#portalMessage'),t[lang].scheduleSaved);await loadPortal((await client.auth.getUser()).data.user)});
  $('#newStudentButton').addEventListener('click',()=>openModal('studentForm'));
  $('#scheduleLessonButton').addEventListener('click',()=>{const form=$('#scheduleForm'),input=form.elements.next_lesson_at;$('#scheduleStudentName').textContent=selected.full_name;form.elements.scheduled_duration_minutes.value=selected.scheduled_duration_minutes||120;$('#cancelLessonButton').classList.toggle('hidden',!selected.next_lesson_at);if(selected.next_lesson_at){const date=new Date(selected.next_lesson_at);input.value=new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16)}else{input.value=''}openModal('scheduleForm')});
  $('#showReportButton').addEventListener('click',()=>{const form=$('#reportForm'),now=new Date(),end=new Date(now.getTime()+120*60000),local=d=>new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString();$('#reportStudentName').textContent=selected.full_name;form.elements.lesson_date.value=local(now).slice(0,10);form.elements.started_at.value=local(now).slice(11,16);form.elements.ended_at.value=local(end).slice(11,16);form.elements.student_signature_name.value='';form.elements.instructor_signature_name.value=profile.full_name;form.elements.student_signature_attested.checked=false;form.elements.instructor_signature_attested.checked=false;openModal('reportForm')});
  $('#connectParentButton').addEventListener('click',()=>{$('#parentStudentName').textContent=selected.full_name;openModal('parentForm')});
  $('#modalBackdrop').addEventListener('click',closeModals);document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',closeModals));
  $('#studentForm').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget,f=new FormData(form),payload=Object.fromEntries(f.entries());const {data,error}=await client.from('students').insert(payload).select(studentFields).single();if(error)return message(form.querySelector('.message'),error.message,true);students.push(data);students.sort((a,b)=>a.full_name.localeCompare(b.full_name));updateStats();selectStudent(data.id);message($('#portalMessage'),t[lang].saved);form.reset();closeModals()});
  $('#scheduleForm').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget,button=e.submitter,nextLesson=new Date(form.elements.next_lesson_at.value),duration=Number(form.elements.scheduled_duration_minutes.value);message(form.querySelector('.message'),'');button.disabled=true;const {data,error}=await client.functions.invoke('notify-lesson-schedule',{body:{student_id:selected.id,next_lesson_at:nextLesson.toISOString(),scheduled_duration_minutes:duration}});button.disabled=false;const failure=data?.error||error?.message;if(failure){const errorText=failure.includes('Schedule conflict:')?t[lang].lessonConflict:failure.includes('Daily limit reached:')?t[lang].dailyLimitReached:failure;return message(form.querySelector('.message'),errorText,true)}const updated=data.student;students=students.map(s=>s.id===updated.id?updated:s);selectStudent(updated.id);updateStats();form.reset();closeModals();message($('#portalMessage'),data.notification_sent?t[lang].scheduleSavedAndNotified:t[lang].scheduleSavedEmailFailed,!data.notification_sent)});
  $('#cancelLessonButton').addEventListener('click',async()=>{if(!selected.next_lesson_at||!window.confirm(t[lang].cancelLessonConfirm))return;const form=$('#scheduleForm'),button=$('#cancelLessonButton');message(form.querySelector('.message'),'');button.disabled=true;const {data,error}=await client.functions.invoke('notify-lesson-schedule',{body:{student_id:selected.id,next_lesson_at:null,scheduled_duration_minutes:selected.scheduled_duration_minutes||120}});button.disabled=false;const failure=data?.error||error?.message;if(failure)return message(form.querySelector('.message'),failure,true);const updated=data.student;students=students.map(s=>s.id===updated.id?updated:s);selectStudent(updated.id);updateStats();form.reset();closeModals();message($('#portalMessage'),data.notification_sent?t[lang].lessonCancelledAndNotified:t[lang].lessonCancelledEmailFailed,!data.notification_sent)});
  $('#reportForm').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget,f=new FormData(form),payload=Object.fromEntries(f.entries()),studentSignature=payload.student_signature_name,instructorSignature=payload.instructor_signature_name;delete payload.student_signature_attested;delete payload.instructor_signature_attested;delete payload.student_signature_name;delete payload.instructor_signature_name;['duration_minutes','overall_score','observation_score','intersections_score','lane_control_score','parking_score','defensive_driving_score'].forEach(k=>{payload[k]=payload[k]===''?null:Number(payload[k])});payload.share_with_parent=f.get('share_with_parent')==='on';payload.student_id=selected.id;payload.instructor_id=profile.user_id;const {data:report,error}=await client.from('lesson_reports').insert(payload).select().single();if(error)return message(form.querySelector('.message'),error.message,true);const signedAt=new Date().toISOString(),attestations=[{lesson_report_id:report.id,student_id:selected.id,signer_kind:'student',signer_name:studentSignature,signer_user_id:null,witnessed_by_user_id:profile.user_id,method:'in_person_witnessed',attestation_text:'Student entered their name after completing the lesson and confirmed the record.',report_snapshot:report,signed_at:signedAt},{lesson_report_id:report.id,student_id:selected.id,signer_kind:'instructor',signer_name:instructorSignature,signer_user_id:profile.user_id,witnessed_by_user_id:profile.user_id,method:'authenticated_staff',attestation_text:'Authenticated instructor confirmed they provided the lesson and the record is accurate.',report_snapshot:report,signed_at:signedAt}],{error:signatureError}=await client.from('lesson_signature_attestations').insert(attestations);if(signatureError)return message(form.querySelector('.message'),`The lesson was saved, but the signatures were not attached: ${signatureError.message}`,true);const changes={};if(payload.overall_score!=null)changes.summit_score=payload.overall_score;if(payload.next_focus)changes.current_focus=payload.next_focus;if(Object.keys(changes).length){const {error:updateError}=await client.from('students').update(changes).eq('id',selected.id);if(updateError)return message(form.querySelector('.message'),updateError.message,true)}const {data:refreshed,error:refreshError}=await client.from('students').select(studentFields).eq('id',selected.id).single();if(refreshError)return message(form.querySelector('.message'),refreshError.message,true);students=students.map(s=>s.id===refreshed.id?refreshed:s);selectStudent(refreshed.id);message($('#portalMessage'),t[lang].saved);form.reset();closeModals();window.dispatchEvent(new CustomEvent('summit:records-changed'))});
  $('#parentForm').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget,button=e.submitter,payload=Object.fromEntries(new FormData(form).entries());payload.student_id=selected.id;button.disabled=true;message(form.querySelector('.message'),'');const {data,error}=await client.functions.invoke('invite-parent',{body:payload});button.disabled=false;if(error)return message(form.querySelector('.message'),error.message,true);message($('#portalMessage'),data.invitation_sent?t[lang].parentInviteSent:t[lang].parentConnected);form.reset();closeModals()});
  $('#changePasswordForm').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget,button=e.submitter,password=form.elements.new_password.value,confirmation=form.elements.confirm_password.value;message(form.querySelector('.message'),'');if(password.length<12)return message(form.querySelector('.message'),t[lang].passwordTooShort,true);if(password!==confirmation)return message(form.querySelector('.message'),t[lang].passwordMismatch,true);button.disabled=true;const {error}=await client.auth.updateUser({password});button.disabled=false;if(error)return message(form.querySelector('.message'),t[lang].setupFailed,true);form.reset();closeModals();message($('#portalMessage'),t[lang].passwordSaved)});
  client.auth.onAuthStateChange((event,session)=>{if(session&&isPasswordSetupLink()&&(event==='PASSWORD_RECOVERY'||event==='SIGNED_IN'))showPasswordSetup()});
  translate();client.auth.getSession().then(({data})=>{if(!data.session)return;if(isPasswordSetupLink())showPasswordSetup();else loadPortal(data.session.user)});
})();
