(() => {
  'use strict';
  const $=s=>document.querySelector(s),portal=()=>window.SummitPortal;
  const copy={
    en:{staffCompliance:'Staff compliance',instructorLicenceRecords:'Instructor licence records',staffComplianceIntro:'Maintain current licence information for every staff member who provides instruction.',staffLicenceIntro:"Enter the information exactly as it appears on the staff member's current licences.",providesInstruction:'This staff member provides driving instruction',staffDriverLicence:"Driver's licence number",staffDriverExpiry:"Driver's licence expiry",instructorLicence:'Driving instructor licence number',instructorLicenceExpiry:'Instructor licence expiry',saveLicenceRecord:'Save licence record',edit:'Edit',current:'Current',expired:'Expired',expiring:'Expiring soon',incomplete:'Incomplete',notInstructor:'Not marked as instructor',missing:'Missing',lastChanged:'Last changed',neverChanged:'No licence changes recorded',saved:'Licence record saved.',required:'Complete all four licence fields for instructional staff.'},
    fr:{staffCompliance:'Conformité du personnel',instructorLicenceRecords:'Dossiers des permis des moniteurs',staffComplianceIntro:'Tenez à jour les renseignements sur les permis de chaque membre du personnel qui donne de la formation.',staffLicenceIntro:'Saisissez les renseignements exactement comme ils figurent sur les permis actuels du membre du personnel.',providesInstruction:'Ce membre du personnel donne de la formation à la conduite',staffDriverLicence:'Numéro de permis de conduire',staffDriverExpiry:'Expiration du permis de conduire',instructorLicence:'Numéro de permis de moniteur',instructorLicenceExpiry:'Expiration du permis de moniteur',saveLicenceRecord:'Enregistrer le dossier de permis',edit:'Modifier',current:'À jour',expired:'Expiré',expiring:'Expire bientôt',incomplete:'Incomplet',notInstructor:'Non désigné comme moniteur',missing:'Manquant',lastChanged:'Dernière modification',neverChanged:'Aucune modification de permis enregistrée',saved:'Dossier de permis enregistré.',required:'Remplissez les quatre champs de permis pour le personnel enseignant.'}
  };
  let audit=[];
  const lang=()=>document.documentElement.lang==='fr'?'fr':'en',tr=k=>copy[lang()][k]||k;
  const esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const date=v=>v?new Intl.DateTimeFormat(lang()==='fr'?'fr-CA':'en-CA',{dateStyle:'medium'}).format(new Date(`${v}T12:00:00`)):'—';
  function state(staff){
    if(!staff.provides_instruction)return {key:'notInstructor',kind:'neutral',missing:[]};
    const fields=[['driver_licence_number',tr('staffDriverLicence')],['driver_licence_expiry',tr('staffDriverExpiry')],['instructor_licence_number',tr('instructorLicence')],['instructor_licence_expiry',tr('instructorLicenceExpiry')]],missing=fields.filter(([key])=>!staff[key]).map(([,label])=>label);
    if(missing.length)return {key:'incomplete',kind:'warning',missing};
    const now=new Date(),soon=new Date(now.getTime()+60*86400000),expiries=[new Date(`${staff.driver_licence_expiry}T23:59:59`),new Date(`${staff.instructor_licence_expiry}T23:59:59`)];
    if(expiries.some(x=>x<now))return {key:'expired',kind:'danger',missing:[]};
    if(expiries.some(x=>x<=soon))return {key:'expiring',kind:'warning',missing:[]};
    return {key:'current',kind:'complete',missing:[]};
  }
  function lastChange(userId){return audit.find(x=>x.staff_user_id===userId)?.changed_at}
  function render(){
    if(!portal().profile)return;
    document.querySelectorAll('#staffCompliancePanel [data-i18n],#staffLicenceForm [data-i18n]').forEach(el=>{if(copy[lang()][el.dataset.i18n])el.textContent=tr(el.dataset.i18n)});
    const staff=portal().instructors,required=staff.filter(x=>x.provides_instruction),ready=required.filter(x=>state(x).key==='current');
    $('#staffComplianceCount').textContent=`${ready.length}/${required.length}`;
    $('#staffComplianceList').innerHTML=staff.map(person=>{const s=state(person),changed=lastChange(person.user_id);return `<article class="staff-compliance-card ${s.kind}"><div class="staff-compliance-person"><strong>${esc(person.full_name)}</strong><small>${esc(person.role)}</small><span class="licence-state">${esc(tr(s.key))}</span></div><dl><div><dt>${esc(tr('staffDriverLicence'))}</dt><dd>${esc(person.driver_licence_number||tr('missing'))}</dd><small>${esc(date(person.driver_licence_expiry))}</small></div><div><dt>${esc(tr('instructorLicence'))}</dt><dd>${esc(person.instructor_licence_number||tr('missing'))}</dd><small>${esc(date(person.instructor_licence_expiry))}</small></div></dl><div class="staff-card-action"><small>${esc(changed?`${tr('lastChanged')}: ${new Date(changed).toLocaleString(lang()==='fr'?'fr-CA':'en-CA')}`:tr('neverChanged'))}</small><button class="small edit-staff-licence" data-staff="${person.user_id}" type="button">${esc(tr('edit'))}</button></div></article>`}).join('');
  }
  async function load(){const {data,error}=await portal().client.from('staff_licence_audit').select('staff_user_id,changed_at').order('changed_at',{ascending:false});if(!error)audit=data||[];$('#staffCompliancePanel').classList.remove('hidden');render()}
  function openForm(person){const form=$('#staffLicenceForm');$('#staffLicenceName').textContent=person.full_name;form.elements.user_id.value=person.user_id;form.elements.provides_instruction.checked=Boolean(person.provides_instruction);['driver_licence_number','driver_licence_expiry','instructor_licence_number','instructor_licence_expiry'].forEach(k=>form.elements[k].value=person[k]||'');form.querySelector('.message').textContent='';form.classList.remove('hidden');$('#modalBackdrop').classList.remove('hidden')}
  window.addEventListener('summit:portal-ready',load);
  new MutationObserver(render).observe(document.documentElement,{attributes:true,attributeFilter:['lang']});
  $('#staffComplianceList').addEventListener('click',e=>{const button=e.target.closest('.edit-staff-licence');if(!button)return;const person=portal().instructors.find(x=>x.user_id===button.dataset.staff);if(person)openForm(person)});
  $('#staffLicenceForm').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget,values=Object.fromEntries(new FormData(form).entries()),userId=values.user_id;delete values.user_id;values.provides_instruction=form.elements.provides_instruction.checked;['driver_licence_number','driver_licence_expiry','instructor_licence_number','instructor_licence_expiry'].forEach(k=>{values[k]=values[k]||null});if(values.provides_instruction&&['driver_licence_number','driver_licence_expiry','instructor_licence_number','instructor_licence_expiry'].some(k=>!values[k])){form.querySelector('.message').textContent=tr('required');return}values.updated_at=new Date().toISOString();const {data,error}=await portal().client.from('staff_profiles').update(values).eq('user_id',userId).select('user_id,full_name,role,provides_instruction,driver_licence_number,driver_licence_expiry,instructor_licence_number,instructor_licence_expiry').single();if(error){form.querySelector('.message').textContent=error.message;return}Object.assign(portal().instructors.find(x=>x.user_id===userId),data);form.classList.add('hidden');$('#modalBackdrop').classList.add('hidden');$('#portalMessage').textContent=tr('saved');await load()});
})();
