(()=>{'use strict';
  const $=s=>document.querySelector(s),portal=()=>window.SummitPortal;
  let student=null,records=[];
  const esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const hours=v=>Number(v||0).toLocaleString('en-CA',{maximumFractionDigits:2});
  const close=()=>{$('#theoryRecordForm').classList.add('hidden');$('#modalBackdrop').classList.add('hidden')};
  async function load(){if(!student)return;const {data,error}=await portal().client.from('theory_training_records').select('*').eq('student_id',student.id).order('session_date',{ascending:false}).order('created_at',{ascending:false});if(error){$('#theoryRecordList').innerHTML=`<p class="message error">${esc(error.message)}</p>`;return}records=data||[];render()}
  function render(){if(!student)return;$('#theoryClassroomTotal').textContent=`${hours(student.classroom_hours)}/20 hours`;$('#theoryFlexibleTotal').textContent=`${hours(student.flexible_hours)}/10 hours`;$('#theoryRecordList').innerHTML=records.map(r=>`<article class="lesson-record ${r.status==='voided'?'is-voided':''}"><div><strong>${esc(r.module_title)}</strong><small>${esc(r.session_date)} · ${esc(String(r.started_at).slice(0,5))}–${esc(String(r.ended_at).slice(0,5))} · ${r.duration_minutes} min</small><span class="theory-record-type">${esc(r.delivery_type)}${r.qa_verified?' · QA verified':''}${r.notes?` · ${esc(r.notes)}`:''}</span></div><div><b>${r.test_score==null?'—':`${r.test_score}%`}</b><em>${esc(r.status)}</em></div></article>`).join('');$('#emptyTheoryRecords').classList.toggle('hidden',records.length>0)}
  function select(next){if(!portal().profile||!['owner','manager'].includes(portal().profile.role))return;student=next;$('#theoryRecordsPanel').classList.remove('hidden');load()}
  window.addEventListener('summit:portal-ready',()=>{if(portal().selected)select(portal().selected)});window.addEventListener('summit:student-selected',e=>select(e.detail.student));
  $('#recordTheoryButton').addEventListener('click',()=>{const form=$('#theoryRecordForm'),now=new Date();$('#theoryStudentName').textContent=`Record session — ${student.full_name}`;form.reset();form.elements.session_date.value=new Date(now.getTime()-now.getTimezoneOffset()*60000).toISOString().slice(0,10);form.elements.instructor_signature_name.value=portal().profile.full_name;form.elements.duration_minutes.value='';form.classList.remove('hidden');$('#modalBackdrop').classList.remove('hidden')});
  function calculate(){const form=$('#theoryRecordForm'),start=form.elements.started_at.value,end=form.elements.ended_at.value;if(!start||!end)return form.elements.duration_minutes.value='';const [sh,sm]=start.split(':').map(Number),[eh,em]=end.split(':').map(Number),minutes=(eh*60+em)-(sh*60+sm);form.elements.duration_minutes.value=minutes>0?minutes:''}
  $('#theoryRecordForm').elements.started_at.addEventListener('change',calculate);$('#theoryRecordForm').elements.ended_at.addEventListener('change',calculate);
  $('#theoryRecordForm').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget,button=e.submitter,payload=Object.fromEntries(new FormData(form).entries());delete payload.student_attested;delete payload.instructor_attested;payload.student_id=student.id;payload.instructor_id=portal().profile.user_id;payload.created_by=portal().profile.user_id;payload.duration_minutes=Number(payload.duration_minutes);payload.test_score=payload.test_score===''?null:Number(payload.test_score);payload.qa_verified=new FormData(form).get('qa_verified')==='on';if(payload.delivery_type==='digital'&&!payload.qa_verified){form.querySelector('.message').textContent='Complete the quality-assurance check for digital training.';return}button.disabled=true;const {error}=await portal().client.from('theory_training_records').insert(payload);button.disabled=false;if(error){form.querySelector('.message').textContent=error.message;return}const {data:refreshed,error:refreshError}=await portal().client.from('students').select(portal().studentFields).eq('id',student.id).single();if(refreshError){form.querySelector('.message').textContent=refreshError.message;return}student=refreshed;portal().setStudents(portal().students.map(s=>s.id===refreshed.id?refreshed:s));close();await load();window.dispatchEvent(new CustomEvent('summit:records-changed'));$('#portalMessage').textContent='Theory training session saved.'});
})();
